name: Node.js CI

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js 17
           uses: actions/setup-node@v1
           with:
              node-version: 17
         - run: npm cache clean --force
         - run: npm ci
         - run: npm run lint
         - run: npm run build --if-present
         - run: npm test
